SET DATABASE TestDB;
DELETE FROM Estudiante WHERE ID = 1;
DELETE FROM Estudiante WHERE ID = 2;
DELETE FROM Estudiante WHERE ID = 3;
DELETE FROM Estudiante WHERE ID = 4;
DROP TABLE Estudiante;
DELETE FROM Producto WHERE ID = 1;
DELETE FROM Producto WHERE ID = 2;
DELETE FROM Producto WHERE ID = 3;
DELETE FROM Producto WHERE ID = 4;
DELETE FROM Producto WHERE ID = 5;
DROP TABLE Producto;
DELETE FROM Categoria WHERE ID = 1;
DELETE FROM Categoria WHERE ID = 2;
DELETE FROM Categoria WHERE ID = 3;
DROP TABLE Categoria